name: sundial_wellness_tracker
description: "This is a modular, efficient, and offline-capable PoC wellness tracker app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  introduction_screen: ^3.1.14
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_hooks: ^0.20.5
  go_router: ^14.6.2
  firebase_crashlytics: ^4.2.0
  http_interceptor: ^2.0.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  very_good_analysis: ^7.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/jsons/
