name: sundial_wellness_tracker
description: "This is a modular, efficient, and offline-capable PoC wellness tracker app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  introduction_screen: ^3.1.14
  equatable: ^2.0.7
  flutter_hooks: ^0.20.5
  go_router: ^14.6.2
  firebase_crashlytics: ^4.2.0
  http_interceptor: ^2.0.0
  intl: ^0.20.1
  lottie: ^3.3.0
  animated_emoji: ^3.1.0
  reactive_forms: ^17.0.0
  liquid_pull_refresh: ^1.0.6
  uuid: ^4.5.1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  very_good_analysis: ^7.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/animations/
    - assets/logos/
    - assets/icons/
    - packages/animated_emoji/lottie/starStruck.json
    - packages/animated_emoji/lottie/partyingFace.json
    - packages/animated_emoji/lottie/smile.json
    - packages/animated_emoji/lottie/relieved.json
    - packages/animated_emoji/lottie/diagonalMouth.json
    - packages/animated_emoji/lottie/sad.json
    - packages/animated_emoji/lottie/anxiousWithSweat.json
    - packages/animated_emoji/lottie/angry.json
    - packages/animated_emoji/lottie/distraught.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
