// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDlyTvnJctd3vWAbHtnRlywpyiEHoowM',
    appId: '1:936289716323:web:34e5539539fd0b6f449056',
    messagingSenderId: '936289716323',
    projectId: 'sundial-wellness-tracker-app',
    authDomain: 'sundial-wellness-tracker-app.firebaseapp.com',
    storageBucket: 'sundial-wellness-tracker-app.firebasestorage.app',
    measurementId: 'G-S3PKSF60DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkgvPkkh2vzR-gsPZP0Tf4UtTznZtX-w',
    appId: '1:936289716323:android:95bdb20b5666de46449056',
    messagingSenderId: '936289716323',
    projectId: 'sundial-wellness-tracker-app',
    storageBucket: 'sundial-wellness-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD337zM7EWqjycl7f3f7xKmu9njAqmO-cE',
    appId: '1:936289716323:ios:c06224c7edf8fc7d449056',
    messagingSenderId: '936289716323',
    projectId: 'sundial-wellness-tracker-app',
    storageBucket: 'sundial-wellness-tracker-app.firebasestorage.app',
    iosBundleId: 'sundial.wellness.tracker.android.apps.sundialWellnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD337zM7EWqjycl7f3f7xKmu9njAqmO-cE',
    appId: '1:936289716323:ios:c06224c7edf8fc7d449056',
    messagingSenderId: '936289716323',
    projectId: 'sundial-wellness-tracker-app',
    storageBucket: 'sundial-wellness-tracker-app.firebasestorage.app',
    iosBundleId: 'sundial.wellness.tracker.android.apps.sundialWellnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbDlyTvnJctd3vWAbHtnRlywpyiEHoowM',
    appId: '1:936289716323:web:d64b9dfee6f55930449056',
    messagingSenderId: '936289716323',
    projectId: 'sundial-wellness-tracker-app',
    authDomain: 'sundial-wellness-tracker-app.firebaseapp.com',
    storageBucket: 'sundial-wellness-tracker-app.firebasestorage.app',
    measurementId: 'G-NFQWH7S63R',
  );
}
